apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ai-task-platform
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: worker
          image: arshiyask/ai-task-worker:38159a129dbc4d8624d9f5a383a65c6b778e99e6
          envFrom:
            - configMapRef:
                name: ai-task-config
            - secretRef:
                name: ai-task-secrets
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
